# Generated by Django 2.0.7 on 2018-07-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
