# Generated by Django 2.0.7 on 2018-07-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180721_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='category',
            field=models.CharField(choices=[('pxjg', '培训机构'), ('gx', '高校'), ('gr', '个人')], default='pxjg', max_length=4),
        ),
    ]
