# Generated by Django 2.0.7 on 2018-07-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organizations_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='course_nums',
            field=models.IntegerField(default=0, verbose_name='课程数量'),
        ),
    ]
