# Generated by Django 2.0.7 on 2018-07-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20180723_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
    ]
