# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 08:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='课程名')),
                ('desc', models.CharField(max_length=200, verbose_name='课程简介')),
                ('detail', models.TextField(verbose_name='课程详情')),
                ('degree', models.CharField(choices=[('junior', '初级'), ('intermediate', '中级'), ('senior', '高级')], max_length=12, verbose_name='难度')),
                ('learn_time', models.IntegerField(verbose_name='学习时长')),
                ('students', models.IntegerField(verbose_name='学习人数')),
                ('image', models.ImageField(max_length=500, upload_to='', verbose_name='课程图片')),
                ('fav_nums', models.IntegerField(verbose_name='收藏人数')),
                ('add_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='章节名')),
                ('add_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Courses', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程章节',
                'verbose_name_plural': '课程章节',
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='资源名称')),
                ('file', models.FileField(upload_to='course/resourses/%Y/%m/%d', verbose_name='资源文件')),
                ('add_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Courses', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程资源',
                'verbose_name_plural': '课程资源',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='视频名')),
                ('add_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Lessons', verbose_name='章节')),
            ],
            options={
                'verbose_name': '课程视频',
                'verbose_name_plural': '课程视频',
            },
        ),
    ]
