# Generated by Django 2.0.7 on 2018-07-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courses_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(max_length=500, upload_to='course/%Y/%m/%d', verbose_name='课程图片'),
        ),
    ]
