# Generated by Django 2.0.7 on 2018-07-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180721_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='course/%Y/%m/%d', verbose_name='课程图片'),
        ),
    ]
