# Generated by Django 2.0.7 on 2018-07-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_courses_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='点击人数'),
        ),
    ]
