# Generated by Django 2.0.7 on 2018-07-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_courses_click_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.CharField(default='后端开发', max_length=10, verbose_name='课程类型'),
        ),
    ]
