# Generated by Django 2.0.7 on 2018-07-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_courses_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='learn_time',
            field=models.IntegerField(default=0, verbose_name='学习分钟数'),
        ),
    ]
