# Generated by Django 2.0.7 on 2018-07-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_videos_learn_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_gain',
            field=models.CharField(default='', max_length=100, verbose_name='学到什么'),
        ),
        migrations.AddField(
            model_name='courses',
            name='konwleage_preparation',
            field=models.CharField(default='', max_length=200, verbose_name='知识准备'),
        ),
    ]
