# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasks',
            name='mobile',
            field=models.IntegerField(verbose_name='用户手机'),
        ),
    ]
