# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_bannders_emailverifyrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.IntegerField(blank=True, null=True, verbose_name='手机'),
        ),
    ]
