# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180716_2020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bannders',
            new_name='Banners',
        ),
    ]
