# Generated by Django 2.0.7 on 2018-07-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180719_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='headshot',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='user/headshot/%Y/%m/%d', verbose_name='头像'),
        ),
    ]
