# Generated by Django 2.0.7 on 2018-07-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180723_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecords',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('updateemail', '修改邮箱')], max_length=11),
        ),
    ]
